services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Liberty10
      MYSQL_DATABASE: Plague_Rat_Character
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./application/init:/docker-entrypoint-initdb.d/
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - appnet

  app:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Liberty10
      MYSQL_DATABASE: Plague_Rat_Character
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    links:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - appnet
    restart: on-failure
networks:
  appnet: